---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netdata-conf-slave
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  stream.conf: |-
    [stream]
        enabled = yes
        destination = {{ template "netdata.name" . }}:{{ .Values.service.port }}
        api key = 11111111-2222-3333-4444-555555555555
        timeout seconds = 60
        buffer size bytes = 1048576
        reconnect delay seconds = 5
        initial clock resync iterations = 60
  netdata.conf: |-
    [global]
        memory mode = ram
    [web]
        mode = none
    [health]
        enabled = no
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: netdata-conf-master
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  stream.conf: |-
    [11111111-2222-3333-4444-555555555555]
        enabled = yes
        history = 3600
        default memory mode = save
        health enabled by default = auto
        allow from = *
  netdata.conf: |-
    [global]
        memory mode = save
        bind to = 0.0.0.0:{{ .Values.service.port }}
  health_alarm_notify.conf: |- # The following is an example. You will need to configure and start the sendmail daemon to use it, or use a different notification method
        SEND_EMAIL="NO"
        SEND_SLACK="YES"
        SLACK_WEBHOOK_URL="{{ .Values.notifications.slackurl }}"
        DEFAULT_RECIPIENT_SLACK="{{ .Values.notifications.slackrecipient }}"
        role_recipients_slack[sysadmin]="${DEFAULT_RECIPIENT_SLACK}"
        role_recipients_slack[domainadmin]="${DEFAULT_RECIPIENT_SLACK}"
        role_recipients_slack[dba]="${DEFAULT_RECIPIENT_SLACK}"
        role_recipients_slack[webmaster]="${DEFAULT_RECIPIENT_SLACK}"
        role_recipients_slack[proxyadmin]="${DEFAULT_RECIPIENT_SLACK}"
        role_recipients_slack[sitemgr]="${DEFAULT_RECIPIENT_SLACK}"

